GET https://fullstackopen-phonebook-backend-grjx.onrender.com/api/persons

###
POST https://fullstackopen-phonebook-backend-grjx.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "0405671234"
}